name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.platformio
        key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini') }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build
      run: >
        pio run
        -e folle
        -e generic_1x_30 -e generic_1x_480 -e generic_1x_960 -e generic_1x_2048
        -e generic_8x_30 -e generic_8x_480 -e generic_8x_960 -e generic_8x_2048
