name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build carre_1
      run: pio run -e carre_1
    - name: Build carre_2
      run: pio run -e carre_2
    - name: Build WS2812_480
      run: pio run -e WS2812_480
    - name: Build WS2812_960
      run: pio run -e WS2812_960
    - name: Build WS2812_2048
      run: pio run -e WS2812_2048
    - name: Build DMX2LEDs_V4_WS2812_480
      run: pio run -e DMX2LEDs_V4_WS2812_480
    - name: Build DMX2LEDs_V4_WS2812_960
      run: pio run -e DMX2LEDs_V4_WS2812_960
    - name: Build DMX2LEDs_V4_WS2812_2048
      run: pio run -e DMX2LEDs_V4_WS2812_2048
    - name: Deploy
      env:
        SUPER_SECRET: ${{ secrets.TOKEN }} 
      run: |
        mv .pio/build/carre_1/firmware.bin     DMX2LEDs_carre_1.bin
        mv .pio/build/carre_2/firmware.bin     DMX2LEDs_carre_2.bin

        mv .pio/build/WS2812_480/firmware.bin     DMX2LEDs_WS2812_480.bin
        mv .pio/build/WS2812_960/firmware.bin     DMX2LEDs_WS2812_960.bin
        mv .pio/build/WS2812_2048/firmware.bin    DMX2LEDs_WS2812_2048.bin

        mv .pio/build/DMX2LEDs_V4_WS2812_480/firmware.bin     DMX2LEDs_V4_WS2812_480.bin
        mv .pio/build/DMX2LEDs_V4_WS2812_960/firmware.bin     DMX2LEDs_V4_WS2812_960.bin
        mv .pio/build/DMX2LEDs_V4_WS2812_2048/firmware.bin    DMX2LEDs_V4_WS2812_2048.bin

        curl -sSF file=@DMX2LEDs_carre_1.bin 'https://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@DMX2LEDs_carre_2.bin 'https://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET

        curl -sSF file=@DMX2LEDs_WS2812_480.bin  'https://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@DMX2LEDs_WS2812_960.bin  'https://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@DMX2LEDs_WS2812_2048.bin 'https://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET

        curl -sSF file=@DMX2LEDs_V4_WS2812_480.bin  'https://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@DMX2LEDs_V4_WS2812_960.bin  'https://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@DMX2LEDs_V4_WS2812_2048.bin 'https://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET

        echo `TZ="Europe/Paris" date '+%F %T'`" git:"`git rev-parse --short HEAD` > DMX2LEDs.info
        curl -sSF file=@DMX2LEDs.info 'https://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET


